title: AI Catalogue
description: A comprehensive catalogue of AI buzzwords and topics, simplified for easy understanding.
baseurl: ""
url: "https://github.malinthar.com" # Replace with your actual domain
twitter_username: malintharanasi1
github_username: malinthar

# Theme settings
theme: minima
markdown: kramdown

# Collections for organizing AI topics
collections:
  topics:
    output: true
    permalink: /topics/:path/
  categories:
    output: true
    permalink: /categories/:path/

# Default layouts for different content types
defaults:
  - scope:
      path: ""
      type: "topics"
    values:
      layout: "topic"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Pagination settings
paginate: 6
paginate_path: "/blog/page:num/"

# Comment out or remove SASS configuration since we're using plain CSS
# sass:
#   sass_dir: _sass
#   style: compressed

# Don't exclude these directories - GitHub Pages needs them
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/